spring:
  profiles:
    active:
    - dev
---
name: a
spring: 
  profiles: dev  #开发环境
  application:
    name: microservicecloud-config-dev
---
name: b
spring:
  profiles: test  #测试环境
  application:
    name: microservicecloud-config-test
