name: application-test
server:
  port: 2222
spring: 
  profiles: test  #测试环境
  application:
    name: microservicecloud-config-test
eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: false
    service-url:
       defaultZone: http://eureka:eureka123@eureka7001.com:7001/eureka/,http://eureka:eureka123@eureka7002.com:7002/eureka/,http://eureka:eureka123@eureka7003.com:7003/eureka/


